### ISSUE TITLE
symbol lookup error: /usr/lib/libIMECore.so.0: undefined symbol: _ZN5fcitx3Log9logStreamEv

### ISSUE THREAD

**Issue by MatthewZMD** [felixonmars/fcitx5-pinyin-zhwiki#23]
I tried to update it through the [AUR](https://aur.archlinux.org/packages/fcitx5-pinyin-zhwiki/), it was working fine until a recent system update, which gives me this error
```
[omitted]
INFO:root:1242000 words generated
INFO:root:1243000 words generated
INFO:root:1244000 words generated
INFO:root:1244188 words generated
libime_pinyindict zhwiki.raw zhwiki.dict
libime_pinyindict: symbol lookup error: /usr/lib/libIMECore.so.0: undefined symbol: _ZN5fcitx3Log9logStreamEv
make: *** [Makefile:26: zhwiki.dict] Error 127
==> ERROR: A failure occurred in build().
    Aborting...
error making: fcitx5-pinyin-zhwiki
```

**Comment by felixonmars** [comment]
Sounds like you are not using libime/fcitx5 from the official repos. Please rebuild your -git package or switch to the official ones.

**Comment by MatthewZMD** [comment]
It was working fine until a recent update, I don't think I switched any of libime/fcitx5 from the official repos. Could you give me a link to the AUR so I'm *100%* sure that I am using the official repo versions?

**Comment by MatthewZMD** [comment]
All good after I decided to reinstall everything fcitx5 related.
