### ISSUE TITLE
如何用 python 直接读取 dict 文件

### ISSUE THREAD

**Issue by metaescape** [felixonmars/fcitx5-pinyin-zhwiki#32]
想用 python 去读取 dict 文件，读取后得到 （词，词的拼音，词的权重或频率） 这样的三元组，请问如何解析这个文件？

**Comment by ipcjs** [comment]
？
维基百科词典没有这些东西🙂

明月拼音的词典倒是有这些东西，可以参考：https://github.com/ipcjs/fcitx5-pinyin-zhwiki/blob/master/convert.py#L154

**Comment by metaescape** [comment]
感谢答复🙏🏻，另外的问题是，我下载了 release 中的 .dict 和 .yaml 文件，这两个的内容是一样吗？比如以下是 yaml 的前几行
我看到 sort by weight 但文件里没有看到权值， 以为 dict 文件里有权重信息。这个 weight 是指什么，从以下来看似乎也不是按频率来排序的。

---
name: zhwiki
version: "0.1"
sort: by_weight
...

吖丙啶  ya bing ding
吖丁啶  ya ding ding
吖啶橙  a ding cheng
吖啶黄  a ding huang
吖啶酮  a ding tong
吖啶    a ding
吖庚环  ya geng huan
......
##...最后几行：
祚建豹蛛        zuo jian bao zhu
胙城县  zuo cheng xian
胙城乡  zuo cheng xiang
胙国    zuo guo
胙土命氏        zuo tu ming shi
胙州    zuo zhou
阼湖    zuo hu
嫲嫲    ma ma

**Comment by ipcjs** [comment]
“感谢”之前能不能先看下我回复了啥？

> 维基百科词典**没有**这些东西🙂

zhwiki原始数据只有纯文本，拼音都是通过`pypinyin`加上去的，怎么会有词频这种东西

**Comment by metaescape** [comment]
好的，谢谢！那这个 sort by weight 没必要加了，容易误导，或者解释 weight 是什么，我最初也默认认为是没有频率的，但点开 yaml 文件看到前几行就写着 sort by weight，另外 .dict 文件不是纯文本，看不到具体内容，以为 .dict里就有了。
