### ISSUE TITLE
为何20231016版本的dict文件只有之前的一半大小？

### ISSUE THREAD

**Issue by debuggerx01** [felixonmars/fcitx5-pinyin-zhwiki#34]
![image](https://github.com/felixonmars/fcitx5-pinyin-zhwiki/assets/19624835/f3c2173f-84de-4e7a-8c25-8db981484bce)
dict.yaml文件的尺寸是增加的，好奇为什么这次的dict文件会比之前小呢？

**Comment by felixonmars** [comment]
因为 libime 1.1.2+ 启用了 zstd 压缩：https://github.com/fcitx/libime/commit/46886ecbe6ee881556975df0944a51df4e08c9ca

**Comment by debuggerx01** [comment]
> 因为 libime 1.1.2+ 启用了 zstd 压缩：[fcitx/libime@46886ec](https://github.com/fcitx/libime/commit/46886ecbe6ee881556975df0944a51df4e08c9ca)

了解了，怪不得我用 libime_pinyindict -d 转换最新的dict文件会报错呢
![image](https://github.com/felixonmars/fcitx5-pinyin-zhwiki/assets/19624835/c58be5e7-5e00-4a7c-a624-c48dc8181aa8)
