### ISSUE TITLE
errrrrrrrrrrrrrrror

### ISSUE THREAD

**Issue by adaaaaaa** [felixonmars/fcitx5-pinyin-zhwiki#5]
zen me an zhuang dou shi zhe ge bao cuo a...miaomiaomiao...
![截图_2020-05-25_12-45-34](https://user-images.githubusercontent.com/23206387/82779105-dcc5a200-9e85-11ea-9d1b-0f10c6511fb6.png)

**Comment by felixonmars** [comment]
I don't think the error has anything to do with this project. Closing.
